/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visao;
import DAO.ConexaoDAO;
import DAO.AdministradorDAO;
import javax.swing.JOptionPane;
import Modelo.Administrador; 
import java.util.ArrayList;
import javax.swing.JTable;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class Listar_Administrador extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listar_Administrador1
     */
    public Listar_Administrador() {
        initComponents();
        try {
            Administrador objadministrador = new Administrador();
            Connection con = ConexaoDAO.AbrirConexao();
            AdministradorDAO dao = new AdministradorDAO(con);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0);

            ArrayList<Administrador> lista = dao.ListarAdministrador();
            int num = 0;
            for(Administrador a :lista){
                model.addRow(new String[num]);
                jTable1.setValueAt(a.getRg_a(), num, 0);
                jTable1.setValueAt(a.getNome_func(), num, 1);
                jTable1.setValueAt(a.getCpf(), num, 2);
                jTable1.setValueAt(a.getSenha(), num, 3);
                jTable1.setValueAt(a.getSexo(), num, 4);
                jTable1.setValueAt(a.getClin(), num, 5);
                jTable1.setValueAt(a.getTel(), num, 6);
                num++;
            }

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,
                "Não foi possivel o encontrar um Administrador!: "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", " " }));
        jComboBox1.setEnabled(false);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 480, -1));

        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 480, -1));

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 330, -1, -1));

        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 480, -1));

        jLabel5.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 14)); // NOI18N
        jLabel5.setText("Sexo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RG_A", "NOME_FUNC", "CPF", "SENHA", "SEXO", "CLIN", "TEL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 545, 287));

        jLabel6.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 14)); // NOI18N
        jLabel6.setText("Tel:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 14)); // NOI18N
        jLabel8.setText("Clínica:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 14)); // NOI18N
        jLabel9.setText("Senha:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 34));

        jLabel1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 24)); // NOI18N
        jLabel1.setText("Listar Administrador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 560, 88));

        jPasswordField1.setEnabled(false);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 479, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 14)); // NOI18N
        jLabel2.setText("Rg_a:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 480, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 14)); // NOI18N
        jLabel3.setText("Nome_Func:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jTextField5.setEnabled(false);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 480, -1));

        jLabel4.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 14)); // NOI18N
        jLabel4.setText("Cpf:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jButton3.setText("Carregar Campos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        jButton4.setText("Limpar Dados");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 330, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/desing (2).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/desing (2).png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/desing (2).png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/desing (2).png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/aaa (2).png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/aaa (2).png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 590, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed
          private void CarregarCampos(){
          jTextField1.setEnabled(false);
          jTextField2.setEnabled(true);
          jTextField3.setEnabled(true);
          jPasswordField1.setEnabled(true);
          jComboBox1.setEnabled(true);
          jTextField5.setEnabled(true);
          jTextField6.setEnabled(true);
          
          int setar = jTable1.getSelectedRow();
          jTextField1.setText(jTable1.getModel().getValueAt(setar, 0).toString());
          jTextField2.setText(jTable1.getModel().getValueAt(setar, 1).toString());
          jTextField3.setText(jTable1.getModel().getValueAt(setar, 2).toString());
          jPasswordField1.setText(jTable1.getModel().getValueAt(setar, 3).toString());
          String sexo = jTable1.getModel().getValueAt(setar, 4).toString();
          jTextField5.setText(jTable1.getModel().getValueAt(setar, 5).toString());
          jTextField6.setText(jTable1.getModel().getValueAt(setar, 6).toString());
           if("M".equals(sexo)){
             jComboBox1.setSelectedIndex(0);
          }
          
          else{
           jComboBox1.setSelectedIndex(1);
          }      
        }
    
            private void LimparDados(){
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jPasswordField1.setText("");
        }
        
            private void AlterarAdministrador(){                  
            int rg_a;
            String nome_func;
            int cpf;
            String senha;
            String sexo;
            String clin;
            int tel;
            
            rg_a = Integer.valueOf(jTextField1.getText());
            nome_func = jTextField2.getText();
            cpf = Integer.valueOf(jTextField3.getText());
            senha = jPasswordField1.getText();
            sexo =  sexo = jComboBox1.getSelectedItem().toString(); 
            clin = jTextField5.getText();
            tel = Integer.valueOf(jTextField6.getText());
            
            Administrador objadministrador = new Administrador();
            objadministrador.setRg_a(rg_a);
            objadministrador.setNome_func(nome_func);
            objadministrador.setCpf(cpf);
            objadministrador.setSenha(senha);
            objadministrador.setSexo(sexo);
            objadministrador.setClin(clin);
            objadministrador.setTel(tel);
            
           
            
            AdministradorDAO objadministradordao = new AdministradorDAO(ConexaoDAO.AbrirConexao());
            objadministradordao.AlterarAdministrador(objadministrador);
       }
        
             private void ExcluirAdministrador(){
             int rg_a;
             
             rg_a = Integer.valueOf(jTextField1.getText());
             
             Administrador objadministrador = new Administrador();
             objadministrador.setRg_a(rg_a);
             
             AdministradorDAO objadministradordao = new AdministradorDAO(ConexaoDAO.AbrirConexao());
             objadministradordao.ExcluirAdministrador(objadministrador);
         }
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       CarregarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       LimparDados();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AlterarAdministrador();
        AdministradorDAO dao = new AdministradorDAO(ConexaoDAO.AbrirConexao());
        ArrayList<Administrador> ListaAdministrador = dao.ListarAdministrador();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        int num = 0;
        for (Administrador adm : ListaAdministrador){
                model.addRow(new String[num]);
                jTable1.setValueAt(adm.getRg_a(), num, 0);
                jTable1.setValueAt(adm.getNome_func(), num, 1);
                jTable1.setValueAt(adm.getCpf(), num, 2);
                jTable1.setValueAt(adm.getSenha(), num, 3);
                jTable1.setValueAt(adm.getSexo(), num, 4);
                jTable1.setValueAt(adm.getClin(), num, 5);
                jTable1.setValueAt(adm.getTel(), num, 6);
                num++;
        }
        LimparDados();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ExcluirAdministrador();
        AdministradorDAO dao = new AdministradorDAO(ConexaoDAO.AbrirConexao());
        ArrayList<Administrador> ListaAdministrador = dao.ListarAdministrador();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        int num = 0;
        for (Administrador a : ListaAdministrador){
                model.addRow(new String[num]);
                jTable1.setValueAt(a.getRg_a(), num, 0);
                jTable1.setValueAt(a.getNome_func(), num, 1);
                jTable1.setValueAt(a.getCpf(), num, 2);
                jTable1.setValueAt(a.getSenha(), num, 3);
                jTable1.setValueAt(a.getSexo(), num, 4);
                jTable1.setValueAt(a.getClin(), num, 5);
                jTable1.setValueAt(a.getTel(), num, 6);
                num++;
        }
        LimparDados();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int rg_a = 0;
        if(!jTextField1.getText().equals("")){
            rg_a = Integer.valueOf(jTextField1.getText());
        }
        
        
        AdministradorDAO objadministradordao = new AdministradorDAO(ConexaoDAO.AbrirConexao());
        ArrayList<Administrador> ListaAdministrador = objadministradordao.BuscarAdministrador(rg_a);
        AdministradorDAO dao = new AdministradorDAO(ConexaoDAO.AbrirConexao());
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        int num = 0;
        for (Administrador a : ListaAdministrador){
                model.addRow(new String[num]);
                jTable1.setValueAt(a.getRg_a(), num, 0);
                jTable1.setValueAt(a.getNome_func(), num, 1);
                jTable1.setValueAt(a.getCpf(), num, 2);
                jTable1.setValueAt(a.getSenha(), num, 3);
                jTable1.setValueAt(a.getSexo(), num, 4);
                jTable1.setValueAt(a.getClin(), num, 5);
                jTable1.setValueAt(a.getTel(), num, 6);
                
                num++;
        }
        LimparDados();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
